#!/usr/bin/env python3
"""
Integrate new charts from experiment file into generate_dashboard.py
Adds: Progress Rings, Timeline Gantt, Radar Chart, Velocity Trend, Heat Map
"""

import re
from pathlib import Path

def main():
    generator_path = Path('/Users/comstudio/Scripts/StudioProcesses/generate_dashboard.py')
    generator_content = generator_path.read_text()

    # Define the new chart HTML sections to be added
    # These will be inserted before the "At-Risk Tasks" section

    new_charts_html = '''
        </div>

        <!-- Progress Rings -->
        <div class="card full-width" style="margin-bottom: 30px; overflow: visible !important; padding: 40px 50px;">
            <h2>📊 Key Performance Metrics</h2>
            <div class="progress-rings-container" style="overflow: visible !important;">
                <div class="progress-ring">
                    <svg class="progress-ring-svg" width="160" height="160">
                        <circle class="progress-ring-circle progress-ring-bg" cx="80" cy="80" r="60"></circle>
                        <circle class="progress-ring-circle progress-ring-progress" cx="80" cy="80" r="60"
                                stroke="#4ecca3" id="ringOnTime"></circle>
                    </svg>
                    <div class="progress-ring-text">
                        <span class="progress-ring-value" id="ringOnTimeValue">0%</span>
                        <span class="progress-ring-label">On-Time Delivery</span>
                    </div>
                </div>
                <div class="progress-ring">
                    <svg class="progress-ring-svg" width="160" height="160">
                        <circle class="progress-ring-circle progress-ring-bg" cx="80" cy="80" r="60"></circle>
                        <circle class="progress-ring-circle progress-ring-progress" cx="80" cy="80" r="60"
                                stroke="#60BBE9" id="ringUtilization"></circle>
                    </svg>
                    <div class="progress-ring-text">
                        <span class="progress-ring-value" id="ringUtilizationValue">0%</span>
                        <span class="progress-ring-label">Team Utilization</span>
                    </div>
                </div>
                <div class="progress-ring">
                    <svg class="progress-ring-svg" width="160" height="160">
                        <circle class="progress-ring-circle progress-ring-bg" cx="80" cy="80" r="60"></circle>
                        <circle class="progress-ring-circle progress-ring-progress" cx="80" cy="80" r="60"
                                stroke="#a78bfa" id="ringProjects"></circle>
                    </svg>
                    <div class="progress-ring-text">
                        <span class="progress-ring-value" id="ringProjectsValue">0</span>
                        <span class="progress-ring-label">Active Projects</span>
                    </div>
                </div>
            </div>
        </div>

        <!-- Timeline Gantt -->
        <div class="card full-width" style="margin-bottom: 30px;">
            <h2>🛸 Project Timeline</h2>
            <p style="color: #a8c5da; margin-top: 5px; margin-bottom: 15px; font-size: 14px;">Next 10 days</p>
            <div class="timeline-container" id="projectTimeline">
                <!-- Timeline will be generated by JavaScript -->
            </div>
        </div>

        <!-- Radar/Spider Chart -->
        <div class="card full-width" style="margin-bottom: 30px; overflow: visible;">
            <h2>🕸️ Workload Balance</h2>
            <p style="color: #a8c5da; margin-top: 5px; margin-bottom: 15px; font-size: 14px;">Actual vs Target distribution across categories</p>
            <div class="radar-container" id="radarChart">
                <!-- Radar will be generated by JavaScript -->
            </div>
        </div>

        <!-- Velocity Trend Chart -->
        <div class="card full-width" style="margin-bottom: 30px;">
            <h2>📈 Team Velocity Trend</h2>
            <p style="color: #a8c5da; margin-top: 5px; margin-bottom: 15px; font-size: 14px;">Projects completed per week over the last 8 weeks</p>
            <div class="velocity-container">
                <canvas id="velocityChart"></canvas>
            </div>
        </div>

        <!-- Heat Map Calendar -->
        <div class="card full-width" style="margin-bottom: 30px;">
            <h2>🔥 Workload Heat Map</h2>
            <p style="color: #a8c5da; margin-top: 5px; margin-bottom: 15px; font-size: 14px;">Daily capacity intensity - Next 10 days</p>
            <div class="heatmap-calendar" id="heatmapCalendar">
                <!-- Heatmap will be generated by JavaScript -->
            </div>
        </div>

        <!-- At-Risk Tasks -->'''

    # Replace the "<!-- At-Risk Tasks -->" line to insert the new charts before it
    generator_content = generator_content.replace(
        '        <!-- At-Risk Tasks -->',
        new_charts_html
    )

    # Now add the JavaScript functions for the new charts
    # Find where to insert them - before the chat widget JavaScript

    js_functions = '''
        // ===== PROGRESS RINGS =====
        function animateProgressRing(elementId, valueId, percentage, isNumber = false) {{
            const ring = document.getElementById(elementId);
            const valueEl = document.getElementById(valueId);
            const radius = 60;
            const circumference = 2 * Math.PI * radius;

            ring.style.strokeDasharray = circumference;
            ring.style.strokeDashoffset = circumference;

            setTimeout(() => {{
                const offset = circumference - (percentage / 100) * circumference;
                ring.style.strokeDashoffset = offset;

                // Animate the number
                let current = 0;
                const target = isNumber ? percentage : percentage;
                const interval = setInterval(() => {{
                    current += isNumber ? 1 : 1;
                    if (current >= target) {{
                        current = target;
                        clearInterval(interval);
                    }}
                    valueEl.textContent = isNumber ? Math.round(current) : Math.round(current) + '%';
                }}, 20);
            }}, 700);
        }}

        // ===== TIMELINE GANTT =====
        function generateTimeline() {{
            const timelineContainer = document.getElementById('projectTimeline');
            if (!timelineContainer) return;

            // Get actual project data from dashboard
            const projects = [
                {{ name: 'Sample Project 1', start: 0, duration: 3, status: 'normal' }},
                {{ name: 'Sample Project 2', start: 2, duration: 4, status: 'warning' }},
                {{ name: 'Sample Project 3', start: 5, duration: 2, status: 'critical' }}
            ];

            const totalDays = 10;
            const dates = [];
            for (let i = 0; i < totalDays; i++) {{
                const date = new Date();
                date.setDate(date.getDate() + i);
                dates.push(date.toLocaleDateString('en-US', {{ month: 'short', day: 'numeric' }}));
            }}

            // Build header
            let html = '<div class="timeline-header">';
            html += '<div class="timeline-project-col">Project</div>';
            html += '<div class="timeline-dates">';
            dates.forEach(date => {{
                html += `<div class="timeline-date">${{date}}</div>`;
            }});
            html += '</div></div>';

            // Build project rows
            projects.forEach(project => {{
                html += '<div class="timeline-row">';
                html += `<div class="timeline-project-name">${{project.name}}</div>`;
                html += '<div class="timeline-bars">';

                const leftPercent = (project.start / totalDays) * 100;
                const widthPercent = (project.duration / totalDays) * 100;

                html += `<div class="timeline-bar ${{project.status}}" style="left: ${{leftPercent}}%; width: ${{widthPercent}}%">${{project.duration}}d</div>`;
                html += '</div></div>';
            }});

            timelineContainer.innerHTML = html;
        }}

        // ===== RADAR/SPIDER CHART =====
        function generateRadarChart() {{
            const container = document.getElementById('radarChart');
            if (!container) return;

            const size = 500;
            const center = size / 2;
            const maxRadius = 150;
            const numLevels = 5;

            // Data: actual vs target percentages
            const categories = [
                {{ name: 'Communications', actual: 67, target: 30 }},
                {{ name: 'Spiritual Formation', actual: 11, target: 25 }},
                {{ name: 'Pastoral/Strategic', actual: 22, target: 20 }},
                {{ name: 'Creative Resources', actual: 0.4, target: 15 }},
                {{ name: 'Partners', actual: 0, target: 5 }}
            ];

            let svg = `<svg class="radar-svg" viewBox="0 0 ${{size}} ${{size}}" width="${{size}}" height="${{size}}">`;

            // Draw grid circles
            for (let i = 1; i <= numLevels; i++) {{
                const r = (maxRadius / numLevels) * i;
                svg += `<circle class="radar-grid" cx="${{center}}" cy="${{center}}" r="${{r}}"/>`;
            }}

            // Draw axes
            const angleStep = (Math.PI * 2) / categories.length;
            categories.forEach((cat, i) => {{
                const angle = angleStep * i - Math.PI / 2;
                const x = center + maxRadius * Math.cos(angle);
                const y = center + maxRadius * Math.sin(angle);
                svg += `<line class="radar-axis" x1="${{center}}" y1="${{center}}" x2="${{x}}" y2="${{y}}"/>`;

                // Labels
                const labelX = center + (maxRadius + 30) * Math.cos(angle);
                const labelY = center + (maxRadius + 30) * Math.sin(angle);
                svg += `<text class="radar-label" x="${{labelX}}" y="${{labelY}}" dy="5">${{cat.name}}</text>`;
            }});

            // Draw target area (dashed)
            let targetPoints = '';
            categories.forEach((cat, i) => {{
                const angle = angleStep * i - Math.PI / 2;
                const r = (cat.target / 100) * maxRadius;
                const x = center + r * Math.cos(angle);
                const y = center + r * Math.sin(angle);
                targetPoints += `${{x}},${{y}} `;
            }});
            svg += `<polygon class="radar-target" points="${{targetPoints}}"/>`;

            // Draw actual area
            let actualPoints = '';
            categories.forEach((cat, i) => {{
                const angle = angleStep * i - Math.PI / 2;
                const r = (cat.actual / 100) * maxRadius;
                const x = center + r * Math.cos(angle);
                const y = center + r * Math.sin(angle);
                actualPoints += `${{x}},${{y}} `;
            }});
            svg += `<polygon class="radar-area" points="${{actualPoints}}"/>`;

            svg += '</svg>';
            container.innerHTML = svg;
        }}

        // ===== VELOCITY TREND CHART =====
        function generateVelocityChart() {{
            const canvas = document.getElementById('velocityChart');
            if (!canvas) return;

            const ctx = canvas.getContext('2d');
            new Chart(ctx, {{
                type: 'line',
                data: {{
                    labels: ['Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6', 'Week 7', 'Week 8'],
                    datasets: [{{
                        label: 'Projects Completed',
                        data: [5, 7, 6, 9, 8, 10, 7, 12],
                        borderColor: '#60BBE9',
                        backgroundColor: 'rgba(96, 187, 233, 0.2)',
                        borderWidth: 3,
                        fill: true,
                        tension: 0.4,
                        pointRadius: 6,
                        pointBackgroundColor: '#60BBE9',
                        pointBorderColor: '#fff',
                        pointBorderWidth: 2,
                        pointHoverRadius: 8,
                        pointHoverBackgroundColor: '#60BBE9',
                        pointHoverBorderColor: '#fff',
                        pointHoverBorderWidth: 3
                    }}]
                }},
                options: {{
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {{
                        legend: {{
                            display: false
                        }}
                    }},
                    scales: {{
                        y: {{
                            beginAtZero: true,
                            ticks: {{
                                stepSize: 2,
                                color: '#a8c5da'
                            }},
                            grid: {{
                                color: 'rgba(96, 187, 233, 0.1)'
                            }}
                        }},
                        x: {{
                            ticks: {{
                                color: '#a8c5da'
                            }},
                            grid: {{
                                color: 'rgba(96, 187, 233, 0.1)'
                            }}
                        }}
                    }}
                }}
            }});
        }}

        // ===== HEAT MAP CALENDAR =====
        function generateHeatMap() {{
            const container = document.getElementById('heatmapCalendar');
            if (!container) return;

            const days = 10;

            // Sample workload intensity data (0-4)
            const intensityData = [4, 4, 2, 3, 1, 0, 2, 3, 4, 2];

            let html = '<div></div>'; // Empty corner cell

            // Header row with dates
            for (let i = 0; i < days; i++) {{
                const date = new Date();
                date.setDate(date.getDate() + i);
                const dateStr = date.toLocaleDateString('en-US', {{ month: 'short', day: 'numeric' }});
                html += `<div class="heatmap-date">${{dateStr}}</div>`;
            }}

            html += '<div class="heatmap-day-label">Workload</div>';

            // Add cells with intensity
            for (let i = 0; i < days; i++) {{
                const intensity = intensityData[i];
                const tasks = Math.round(intensity * 7); // 0-28 tasks
                html += `<div class="heatmap-cell intensity-${{intensity}}" title="${{tasks}} tasks">${{tasks}}</div>`;
            }}

            container.innerHTML = html;
        }}

        // Initialize all new charts
        document.addEventListener('DOMContentLoaded', () => {{
            // Animate progress rings with real data
            animateProgressRing('ringOnTime', 'ringOnTimeValue', {delivery_metrics['on_time_rate']:.0f});
            animateProgressRing('ringUtilization', 'ringUtilizationValue', {team_utilization_avg:.0f});
            animateProgressRing('ringProjects', 'ringProjectsValue', {total_tasks}, true);

            // Generate all charts
            setTimeout(() => {{
                generateTimeline();
                generateRadarChart();
                generateVelocityChart();
                generateHeatMap();
            }}, 100);
        }});

'''

    # Find the location to insert JS functions - before the chat widget script section
    # Look for "document.addEventListener('DOMContentLoaded', function() {" for chat
    chat_js_pattern = r"(        document\.addEventListener\('DOMContentLoaded', function\(\) \{\s*// Chat widget initialization)"

    if re.search(chat_js_pattern, generator_content):
        generator_content = re.sub(
            chat_js_pattern,
            js_functions + r'\n\1',
            generator_content
        )
    else:
        # Fallback: insert before the chat widget HTML section
        generator_content = generator_content.replace(
            '    html += """',
            js_functions + '\n    html += """'
        )

    # Save the updated generator
    generator_path.write_text(generator_content)

    print("✅ Successfully integrated new charts into generate_dashboard.py")
    print("   - Added Progress Rings (3 circular metrics)")
    print("   - Added Timeline Gantt chart")
    print("   - Added Radar/Spider chart for workload balance")
    print("   - Added Velocity Trend chart (Chart.js)")
    print("   - Added Heat Map calendar")
    print("   - Added JavaScript initialization code")

if __name__ == "__main__":
    main()
