"""
Studio Command Center - FastAPI Backend
Serves static HTML dashboard generated by generate_dashboard.py
"""

import logging
from contextlib import asynccontextmanager
from pathlib import Path
import sys
import os

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from app.config import settings
from app.routers import health, dashboard
from app.services.scheduler import start_scheduler, stop_scheduler

# Add the parent directory to Python path to import generate_dashboard
sys.path.append(str(Path(__file__).parent.parent))
import generate_dashboard

# Configure logging
logging.basicConfig(
    level=logging.INFO if settings.environment == "production" else logging.DEBUG,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Static files directory - simplified path
STATIC_DIR = Path(__file__).parent / "static"
# Reports directory where generate_dashboard.py creates the HTML
REPORTS_DIR = Path(__file__).parent.parent / "Reports"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage app lifecycle - startup and shutdown."""
    logger.info(f"Studio Command Center backend starting (environment={settings.environment})")
    logger.info(f"Static files directory: {STATIC_DIR}")
    logger.info(f"Reports directory: {REPORTS_DIR}")

    # Ensure Reports directory exists
    REPORTS_DIR.mkdir(exist_ok=True)

    # Generate initial dashboard on startup
    try:
        logger.info("Generating initial dashboard...")
        generate_dashboard.main()
        logger.info("Initial dashboard generated successfully")
    except Exception as e:
        logger.error(f"Failed to generate initial dashboard: {e}")

    # Start background scheduler
    start_scheduler()
    logger.info("Background scheduler started")

    yield

    # Cleanup on shutdown
    stop_scheduler()
    logger.info("Studio Command Center backend shutting down")


app = FastAPI(
    title=settings.app_name,
    description="Backend API for Studio Command Center - real-time Asana dashboard",
    version=settings.app_version,
    lifespan=lifespan,
)

# CORS middleware - allow all origins for development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(health.router)
app.include_router(dashboard.router)

# Debug static directory path
logger.info(f"Looking for static files at: {STATIC_DIR}")
logger.info(f"Static directory exists: {STATIC_DIR.exists()}")

# List all possible frontend locations for debugging
possible_paths = [
    STATIC_DIR,
    Path(__file__).parent.parent / "frontend" / "dist",
    Path(__file__).parent.parent / "build",
    Path(__file__).parent / "static"
]

for path in possible_paths:
    logger.info(f"Checking path {path}: exists={path.exists()}")
    if path.exists():
        logger.info(f"Contents of {path}: {list(path.iterdir())}")

# Mount static files if the directory exists
if STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")
    logger.info(f"Mounted static files from: {STATIC_DIR}")
else:
    logger.warning(f"Static directory not found: {STATIC_DIR}")

# Mount Reports directory as static files for serving the generated dashboard
if REPORTS_DIR.exists():
    app.mount("/reports", StaticFiles(directory=str(REPORTS_DIR)), name="reports")
    logger.info(f"Mounted reports files from: {REPORTS_DIR}")
else:
    logger.warning(f"Reports directory not found: {REPORTS_DIR}")


@app.get("/{full_path:path}")
async def serve_spa(request: Request, full_path: str):
    """
    Catch-all route to serve index.html for the SPA.
    This handles client-side routing for React.
    """
    # Don't intercept API routes
    if full_path.startswith("api/"):
        return JSONResponse(status_code=404, content={"detail": "API endpoint not found"})

    # For root path, serve the generated dashboard
    if full_path == "" or full_path == "index.html":
        dashboard_file = REPORTS_DIR / "capacity_dashboard.html"
        if dashboard_file.exists():
            return FileResponse(str(dashboard_file))

        # Fallback to static index.html if dashboard not generated yet
        index_file = STATIC_DIR / "index.html"
        if index_file.exists():
            return FileResponse(str(index_file))

    # Try to serve other static files
    if STATIC_DIR.exists():
        static_file = STATIC_DIR / full_path
        if static_file.exists() and static_file.is_file():
            return FileResponse(str(static_file))

    # No static files available
    return JSONResponse(
        status_code=200,
        content={
            "message": f"{settings.app_name} API is running",
            "version": settings.app_version,
            "environment": settings.environment,
            "note": "Frontend not yet deployed or static files not found"
        },
    )